port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
mode: rule
log-level: info
allow-lan: true
external-controller: 0.0.0.0:9090
secret : ""
bind-address: "*"
external-ui: yacd-gh-pages
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  listen: 127.0.0.1:7894
  use-hosts: true
  nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - https://dns.google/dns-query
    - tls://dns.google
    - https://cloudflare-dns.com/dns-query
    - tls://1dot1dot1dot1.cloudflare-dns.com
  fallback:
    - https://dns.google/dns-query
    - tls://dns.google
proxy-providers:
  Simcard:
    type: file
    path: "./simcard.yaml"
    health-check:
      enable: false
      url: http://www.gstatic.com/generate_204
      interval: 300     
#Gunakan tanda pagar menghiden, jika salah satu server tidak kepakai
proxy-groups:
- name: SIMASTER
  type: select
  disable-udp: false
  proxies:
    - SELECT
    - PING
    - FALLBACK
    - LOADBALANCE
    - RELAY
  url: http://www.gstatic.com/generate_204
  interval: '99'
- name: SELECT
  type: select
  disable-udp: false
  use:
    - Simcard
  url: http://www.gstatic.com/generate_204
  interval: '99'
- name: PING
  type: url-test
  disable-udp: false
  use:
    - Simcard
  url: http://www.gstatic.com/generate_204
  interval: '99'
- name: FALLBACK
  type: fallback
  disable-udp: false
  use:
    - Simcard
  url: http://www.gstatic.com/generate_204
  interval: '99'
- name: LOADBALANCE
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
    - Simcard
  url: http://www.gstatic.com/generate_204
  interval: '99'
- name: RELAY
  type: relay
  disable-udp: false
  use:
    - Simcard
  url: http://www.gstatic.com/generate_204
  interval: '99'
rules:
- DOMAIN-KEYWORD,google,SIMASTER
- DOMAIN-KEYWORD,youtube,SIMASTER
- DOMAIN-KEYWORD,facebook,SIMASTER
- DOMAIN-KEYWORD,instagram,SIMASTER
- DOMAIN-KEYWORD,whatsapp,SIMASTER
- DOMAIN-KEYWORD,tiktok,SIMASTER
- MATCH,SIMASTER
tun:
  enable: true
  stack: system
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
  - tcp://any:53
profile:
  store-selected: true
  store-fake-ip: true
